const data = {
  bread: {
  image: "bread_image.jpg",
  items: [
    {
      id: 1,
      category: "Bread",
      name: "Bread 1",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 2,
      category: "Bread",
      name: "Bread 2",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 3,
      category: "Bread",
      name: "Bread 3",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 4,
      category: "Bread",
      name: "Bread 4",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 5,
      category: "Bread",
      name: "Bread 5",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 6,
      category: "Bread",
      name: "Bread 6",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 7,
      category: "Bread",
      name: "Bread 7",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 8,
      category: "Bread",
      name: "Bread 8",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 9,
      category: "Bread",
      name: "Bread 9",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 10,
      category: "Bread",
      name: "Bread 10",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 11,
      category: "Bread",
      name: "Bread 11",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 12,
      category: "Bread",
      name: "Bread 12",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 13,
      category: "Bread",
      name: "Bread 13",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 14,
      category: "Bread",
      name: "Bread 14",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 15,
      category: "Bread",
      name: "Bread 15",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 16,
      category: "Bread",
      name: "Bread 16",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
  ],
},
  cakes: {
  image: "cakes_image.jpg",
  items: [
    {
      id: 1,
      category: "Cake",
      name: "Cake 1",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 2,
      category: "Cake",
      name: "Cake 2",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 3,
      category: "Cake",
      name: "Cake 3",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 4,
      category: "Cake",
      name: "Cake 4",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 5,
      category: "Cake",
      name: "Cake 5",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 6,
      category: "Cake",
      name: "Cake 6",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 7,
      category: "Cake",
      name: "Cake 7",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 8,
      category: "Cake",
      name: "Cake 8",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 9,
      category: "Cake",
      name: "Cake 9",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 10,
      category: "Cake",
      name: "Cake 10",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 11,
      category: "Cake",
      name: "Cake 11",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 12,
      category: "Cake",
      name: "Cake 12",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 13,
      category: "Cake",
      name: "Cake 13",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 14,
      category: "Cake",
      name: "Cake 14",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 15,
      category: "Cake",
      name: "Cake 15",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 16,
      category: "Cake",
      name: "Cake 16",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
  ],
},
pastry: {
  image: "pastry_image.jpg",
  items: [
    {
      id: 1,
      category: "Pastry",
      name: "Pastry 1",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 2,
      category: "Pastry",
      name: "Pastry 2",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 3,
      category: "Pastry",
      name: "Pastry 3",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 4,
      category: "Pastry",
      name: "Pastry 4",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 5,
      category: "Pastry",
      name: "Pastry 5",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 6,
      category: "Pastry",
      name: "Pastry 6",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 7,
      category: "Pastry",
      name: "Pastry 7",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 8,
      category: "Pastry",
      name: "Pastry 8",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 9,
      category: "Pastry",
      name: "Pastry 9",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 10,
      category: "Pastry",
      name: "Pastry 10",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 11,
      category: "Pastry",
      name: "Pastry 11",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 12,
      category: "Pastry",
      name: "Pastry 12",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
  ],
},
  coffee: {
  image: "coffee_image.jpg",
  items: [
    {
      id: 1,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 2,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 3,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 4,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 5,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 6,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 7,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 8,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 9,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 10,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 11,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 12,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 13,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 14,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
    {
      id: 15,
      category: "Coffee",
      name: "",
      description: "",
      image: "",
      nutrition: {
        calories: null,
        fat: null,
        sodium: null,
        carbs: null,
      },
    },
  ],
},
  tea: {
    image: "tea_image.jpg", // Add the image key at the top level
    items: [
      {
        id: 1,
        category: "Tea",
        name: "",
        description: "",
        image: "",
        nutrition: {
          calories: null,
          fat: null,
          sodium: null,
          carbs: null,
        },
      },
      {
        id: 2,
        category: "Tea",
        name: "",
        description: "",
        image: "",
        nutrition: {
          calories: null,
          fat: null,
          sodium: null,
          carbs: null,
        },
      },
      {
        id: 3,
        category: "Tea",
        name: "",
        description: "",
        image: "",
        nutrition: {
          calories: null,
          fat: null,
          sodium: null,
          carbs: null,
        },
      },
      {
        id: 4,
        category: "Tea",
        name: "",
        description: "",
        image: "",
        nutrition: {
          calories: null,
          fat: null,
          sodium: null,
          carbs: null,
        },
      },
      {
        id: 5,
        category: "Tea",
        name: "",
        description: "",
        image: "",
        nutrition: {
          calories: null,
          fat: null,
          sodium: null,
          carbs: null,
        },
      },
      {
        id: 6,
        category: "Tea",
        name: "",
        description: "",
        image: "",
        nutrition: {
          calories: null,
          fat: null,
          sodium: null,
          carbs: null,
        },
      },
      {
        id: 7,
        category: "Tea",
        name: "",
        description: "",
        image: "",
        nutrition: {
          calories: null,
          fat: null,
          sodium: null,
          carbs: null,
        },
      },
      {
        id: 8,
        category: "Tea",
        name: "",
        description: "",
        image: "",
        nutrition: {
          calories: null,
          fat: null,
          sodium: null,
          carbs: null,
        },
      },
      {
        id: 9,
        category: "Tea",
        name: "",
        description: "",
        image: "",
        nutrition: {
          calories: null,
          fat: null,
          sodium: null,
          carbs: null,
        },
      },
    ],
  },

  blended: {
    image: "blended_image.jpg", // Add the image key at the top level
    items: [
      {
        id: 1,
        category: "Blended",
        name: "",
        description: "",
        image: "",
        nutrition: {
          calories: null,
          fat: null,
          sodium: null,
          carbs: null,
        },
      },
      {
        id: 2,
        category: "Blended",
        name: "",
        description: "",
        image: "",
        nutrition: {
          calories: null,
          fat: null,
          sodium: null,
          carbs: null,
        },
      },
      {
        id: 3,
        category: "Blended",
        name: "",
        description: "",
        image: "",
        nutrition: {
          calories: null,
          fat: null,
          sodium: null,
          carbs: null,
        },
      },
      {
        id: 4,
        category: "Blended",
        name: "",
        description: "",
        image: "",
        nutrition: {
          calories: null,
          fat: null,
          sodium: null,
          carbs: null,
        },
      },
      {
        id: 5,
        category: "Blended",
        name: "",
        description: "",
        image: "",
        nutrition: {
          calories: null,
          fat: null,
          sodium: null,
          carbs: null,
        },
      },
    ],
  },
};

export default data;
