const data = {
  bread: {
  headerImage: "../images/menu-headers/bread-header.webp",
  items: [
    {
      id: 1,
      category: "Bread",
      name: "Salt & Butter Roll",
      ingredients: "Bread dough(wheat flour, milk, water, sugar, prepared edible fat, shortening, mixed skim milk powder, yeast, sea salt, dough improver, propylene glycol alginate, prepared edible fat, milk cream, xanthan gum), Egg wash(egg, water)",
      image: "../images/bread/salt-butter.png",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '20(g)',
          carbs: '44(g)',
          protein: '8(g)',
        },
    },
    {
      id: 2,
      category: "Bread",
      name: "Buttercream Bread",
      ingredients: "Bread dough(wheat flour, water, margarine, whole egg, sugar, mixed skim milk powder, yeast, whipping cream, sea salt, bread improver, yeast, skimmed milk powder), Butter cream, Egg wash(egg, water)Bread dough(wheat flour, water, margarine, whole egg, sugar, mixed skim milk powder, yeast, whipping cream, sea salt, bread improver, yeast, skimmed milk powder), Butter cream, Egg wash(egg, water)",
      image: "../images/bread/buttercream-bread.webp",
      nutrition: {
          calories: 350,
          fat: '22(g)',
          fatS:'5(g)',
          tfat:'4(g)',
          sugar: '11(g)',
          carbs: '34(g)',
          protein: '5(g)',
        },
    },
    {
      id: 3,
      category: "Bread",
      name: "Blueberry Cream Cheese Bread",
      ingredients: "Dough[wheat flour, cream cheese, sugared dried blueberries, blueberry jam, milk, sugar, egg yolk, prepared edible fat, corn starch, all purpose flour, xanthan gum, ε-polylysine, water, glutinous flour(tapioca starch), whole egg, sugar, margarine, yeast, sea salt, bread improver, whipping cream, yeast, skimmed milk powder], Sliced almond",
      image: "../images/bread/blueberry-cream.webp",
      nutrition: {
          calories: 200,
          fat: '7(g)',
          fatS:'3.5(g)',
          tfat:'0(g)',
          sugar: '7(g)',
          carbs: '27(g)',
          protein: '4(g)',
        },
    },
    {
      id: 4,
      category: "Bread",
      name: "Raisin Bread",
      ingredients: "Bread dough(wheat flour, water, dried raisin, sugar, milk, liquid egg, shortening, yeast, sea salt, dough improver, Egg wash(egg, water)",
      image: "../images/bread/rasin-bread.webp",
      nutrition: {
          calories: 280,
          fat: '6(g)',
          fatS:'1(g)',
          tfat:'0(g)',
          sugar: '14(g)',
          carbs: '48(g)',
          protein: '7(g)',
        },
    },
    {
      id: 5,
      category: "Bread",
      name: "Multi-Grain Pan Bread",
      ingredients: "Bread dough(wheat flour, water, sunflower seed, pumpkin seed, multi grain mix(sesame), liquid egg, sugar, yeast, margarine, butter, dough improver, skimmed milk powder, sea salt), Egg wash(egg, water)",
      image: "../images/bread/multi-grain.webp",
      nutrition: {
          calories: 290,
          fat: '9(g)',
          fatS:'2(g)',
          tfat:'0(g)',
          sugar: '5(g)',
          carbs: '43(g)',
          protein: '10(g)',
        },
    },
    {
      id: 6,
      category: "Bread",
      name: "Sweet Frank Roll",
      ingredients: "Bread dough(wheat flour, water, liquid egg, sugar, milk, butter, margarine, heavy cream, yeast, milk powder, dough improver, sea salt), Beef franks, Shredded mozzarella, Egg wash(egg, water), Parsley flakes",
      image: "../images/bread/sweet-frank.webp",
      nutrition: {
          calories: 3000,
          fat: '18(g)',
          fatS:'8(g)',
          tfat:'1(g)',
          sugar: '5(g)',
          carbs: '23(g)',
          protein: '11(g)',
        },
    },
    {
      id: 7,
      category: "Bread",
      name: "Croque Monsieur",
      ingredients: "Whipping cream pan bread(wheat flour, water, milk, sugar, heavy cream, liquid egg, butter, margarine, milk powder, yeast, sea salt, dough improver), Cloud cream[heavy cream(milk), whipped cream, sugar], Shredded mozzarella, Sliced ham(pork), Sliced american cheese, Mayonnaise, Dried parsley",
      image: "../images/bread/croque-monsieur.webp",
      nutrition: {
          calories: 680,
          fat: '51(g)',
          fatS:'24(g)',
          tfat:'1(g)',
          sugar: '10(g)',
          carbs: '29(g)',
          protein: '23(g)',
        },
    },
    {
      id: 8,
      category: "Bread",
      name: "Soboro Bread",
      ingredients: "Soboro bun[wheat flour, water, liquid egg, sugar, milk, butter, margarine, heavy cream(milk), yeast, milk powder, dough improver, sea salt], Soboro topping[wheat flour, sugar, margarine, peanut butter, chopped peanuts, corn powder, whole egg, corn syrup, baking powder, baking soda, sea salt, artificial flavor(peanut)], Soboro bun biscuit[wheat flour, margarine, sugar, peanut butter, chopped peanuts, corn powder, whole egg, baking powder, baking soda, sea salt, artificial flavor(peanut)], Egg wash(egg, water)",
      image: "../images/bread/soboro-bread.webp",
      nutrition: {
          calories: 260,
          fat: '11(g)',
          fatS:'3(g)',
          tfat:'1(g)',
          sugar: '12(g)',
          carbs: '35(g)',
          protein: '6(g)',
        },
    },
    {
      id: 9,
      category: "Bread",
      name: "Custard Bun",
      ingredients: "Filling[milk, sugar, egg yolk, prepared edible fat, corn starch, all purpose flour, xanthan gum, ε-polylysine], Dough[wheat flour, water, sugar, margarine, whole egg, egg yolk, milk, yeast, mixed skim milk powder, sea salt, dough improver, dark brown sugar, yeast, vanilla flavored syrup, yeast food, skimmed mlikpowder], Sliced almond, Egg wash(egg, water)",
      image: "../images/bread/custard-bun.webp",
      nutrition: {
          calories: 190,
          fat: '8(g)',
          fatS:'2.5(g)',
          tfat:'0(g)',
          sugar: '9(g)',
          carbs: '26(g)',
          protein: '4(g)',
        },
    },
    {
      id: 10,
      category: "Bread",
      name: "Whole Milk Loaf",
      ingredients: "Bread dough(wheat flour, milk, water, sugar, prepared edible fat, shortening, mixed skim milk powder, yeast, sea salt, dough improver, propylene glycol alginate, prepared edible fat, milk cream, xanthan gum), Egg wash(egg, water)",
      image: "../images/bread/whole-milk.webp",
      nutrition: {
          calories: 270,
          fat: '6(g)',
          fatS:'2.5(g)',
          tfat:'0(g)',
          sugar: '8(g)',
          carbs: '44(g)',
          protein: '8(g)',
        },
    },
    {
      id: 11,
      category: "Bread",
      name: "Red Bean Bread",
      ingredients: "Bread dough(red bean paste, wheat flour, water, sugar, margarine, whole egg, egg yolk, milk, yeast, mixed skimmed milk powder, sea salt, bread improver, dark brown sugar, skimmed milk powder, vanilla flavored syrup, yeast, yeast food), Cloud cream[heavy cream(milk), whipped cream, sugar], Egg wash(egg, water), Black sesame",
      image: "../images/bread/red-bean.webp",
      nutrition: {
          calories: 240,
          fat: '4.5(g)',
          fatS:'1(g)',
          tfat:'0(g)',
          sugar: '5(g)',
          carbs: '43(g)',
          protein: '5(g)',
        },
    },
    {
      id: 12,
      category: "Bread",
      name: "Milk Cream Bread",
      ingredients: "Milk cream(milk, sugar, whipping cream, condensed milk, egg white, prepared edible fat, waxy corn starch, wheat flour, xanthan gum, vanilla extract, milk flavor), Dough(wheat flour, sugar, prepared edible fat, mixed skimmed milk power, yeast, sea salt, dough improver, yeast food)",
      image: "../images/bread/milk-cream.webp",
      nutrition: {
          calories: 180,
          fat: '6(g)',
          fatS:'3(g)',
          tfat:'1(g)',
          sugar: '9(g)',
          carbs: '26(g)',
          protein: '4(g)',
        },
    },
    {
      id: 13,
      category: "Bread",
      name: "Purple Sweet Potato Loaf",
      ingredients: "Bread dough(wheat flour, water, sugar, milk, margarine, yeast, liquid egg, taro powder, purple sweet potato mix, sea salt, dough improver, skimmed milk powder, ube flavoring extract), Egg wash(egg, water)",
      image: "../images/bread/purple-sweet.webp",
      nutrition: {
          calories: 260,
          fat: '5(g)',
          fatS:'1(g)',
          tfat:'1(g)',
          sugar: '7(g)',
          carbs: '45(g)',
          protein: '7(g)',
        },
    },
    {
      id: 14,
      category: "Bread",
      name: "Taro Cream Bread",
      ingredients: "Bread dough(wheat flour, water, sugar, milk, shortening, taro powder, liquid egg, yeast, dough Improver, sea salt, ube flavoring), Taro butter cream(butter cream, taro powder), Taro almond cream(almond cream, taro powder)",
      image: "../images/bread/taro-cream.webp",
      nutrition: {
          calories: 550,
          fat: '30(g)',
          fatS:'6(g)',
          tfat:'4(g)',
          sugar: '16(g)',
          carbs: '59(g)',
          protein: '11(g)',
        },
    },
    {
      id: 15,
      category: "Bread",
      name: "Potato Cheese Bread",
      ingredients: "Filling(milk, cream cheese, steamed potato, sugar, egg white, condensed milk, soft wheat flour, waxy corn starch, whipping cream, sea salt, locust bean gum), Bread dough(glutinous flour, water, steamed potato, wheat flour, margarine, sugar, food starch, whole egg, soybean oil, cheddar cheese, sea salt, mixed skim milk powder, roasted potato flavoring), Topping(steamed potato, olive oil, wheat flour, potato powder, sugar, sea salt, roasted potato flavoring)",
      image: "../images/bread/potato-cheese.jpeg",
      nutrition: {
          calories: 410,
          fat: '17(g)',
          fatS:'5(g)',
          tfat:'2(g)',
          sugar: '11(g)',
          carbs: '55(g)',
          protein: '5(g)',
        },
    },
    {
      id: 16,
      category: "Bread",
      name: "Honey Cheese Mochi Pancake",
      ingredients: "Bread dough(glutinous flour, water, wheat flour, margarine, cheddar cheese, food starch, whole egg, soybean oil, parmesan cheese, sugar, sea salt, mixed skim milk powder, grated parmesan cheese), Filling(cream cheese, milk, sugar, milk2, whipping cream, egg white, condensed milk, wheat flour, waxy corn starch, locust bean gum, xanthan gum), Honey",
      image: "../images/bread/honey-cheese.webp",
      nutrition: {
          calories: 400,
          fat: '20(g)',
          fatS:'6(g)',
          tfat:'0(g)',
          sugar: '11(g)',
          carbs: '47(g)',
          protein: '6(g)',
        },
    },
  ],
},
  cakes: {
  headerImage: "../images/menu-headers/cake-header2.jpeg",
  items: [
    {
      id: 1,
      category: "Cake",
      name: "Strawberry Sweet",
      ingredients: "Strawberry cake sheet[liquid egg, sugar, wheat flour, butter, strawberry syrup, strawberry powder, emulsifying agent, baking powder, sea salt, food coloring(pink)], Butter, Margareine, Butter cream, Sugar, Water, Strawberry preserve, Strawberry crunch, Strawberry flavor paste, Lemon juice, Corn syrup, Food coloring(pink), Gold leaf",
      image: "../images/cake/strawberry-sweet.png",
      nutrition: {
          calories: 480,
          fat: '30(g)',
          fatS:'15(g)',
          tfat:'1(g)',
          sugar: '25(g)',
          carbs: '26(g)',
          protein: '5(g)',
        },
    },
    {
      id: 2,
      category: "Cake",
      name: "Blueberry Yogurt 3",
      ingredients: "Blueberry cream[heavy cream(milk), blueberry puree, whipped cream, sugar, blueberry compound], White cake sheet(whole egg, wheat flour, sugar, egg white, milk, corn syrup, shortening, margarine, emulsifying agent, corn starch, baking powder, salt, citric acid, xanthan gum), Blueberry, Cloud cream[heavy cream(milk), whipped cream, sugar], Simple syrup(water, sugar, lemon juice), Blueberry glaze(Blueberry compound, water, sugar, lemon juice), Glaze",
      image: "../images/cake/blueberry-yogurt3.png",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 3,
      category: "Cake",
      name: "Blueberry Yogurt 2",
      ingredients: "Blueberry cream[heavy cream(milk), blueberry puree, whipped cream, sugar, blueberry compound], White cake sheet(whole egg, wheat flour, sugar, egg white, milk, corn syrup, shortening, margarine, emulsifying agent, corn starch, baking powder, salt, citric acid, xanthan gum), Blueberry, Cloud cream[heavy cream(milk), whipped cream, sugar], Simple syrup(water, sugar, lemon juice), Blueberry glaze(Blueberry compound, water, sugar, lemon juice), Glaze",
      image: "../images/cake/blueberry-yogurt2.png",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 4,
      category: "Cake",
      name: "Strawberry Lychee",
      ingredients: "Strawberry Lychee cake sheet[liquid egg, sugar, wheat flour, butter, strawberry syrup, strawberry powder, emulsifying agent, baking powder, sea salt, food coloring(pink)], Lychee, Butter, Margareine, Butter cream, Sugar, Water, Strawberry preserve, Strawberry crunch, Strawberry flavor paste, Lemon juice, Corn syrup, Food coloring(pink)",
      image: "../images/cake/strawberry-lychee.png",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 5,
      category: "Cake",
      name: "Strawberry Gateau",
      ingredients: "Strawberry cake sheet[liquid egg, sugar, wheat flour, butter, strawberry syrup, strawberry powder, emulsifying agent, baking powder, sea salt, food coloring(pink)], Butter, Margareine, Butter cream, Sugar, Water, Strawberry preserve, Strawberry crunch, Strawberry flavor paste, Lemon juice, Corn syrup, Food coloring(pink)",
      image: "../images/cake/strawberry-gateau.png",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 6,
      category: "Cake",
      name: "Cloud Cake 3",
      ingredients: "Cloud cream[heavy cream(milk), whipped cream, sugar], White cake sheet(whole egg, wheat flour, sugar, egg white, milk, corn syrup, shortening, margarine, emulsifying agent, corn starch, baking powder, salt, citric acid, xanthan gum), Strawberry, Simple syrup(water, sugar, lemon juice), Green grapes, Red grapes, Blackberry, Blueberry, Raspberry, Glaze, Chocolate sign board(dark)",
      image: "../images/cake/cloud-cake3.png",
      nutrition: {
          calories: 290,
          fat: '22(g)',
          fatS:'13(g)',
          tfat:'1(g)',
          sugar: '15(g)',
          carbs: '22(g)',
          protein: '4(g)',
        },
    },
    {
      id: 7,
      category: "Cake",
      name: "Cloud Cake 2",
      ingredients: "Cloud cream[heavy cream(milk), whipped cream, sugar], White cake sheet(whole egg, wheat flour, sugar, egg white, milk, corn syrup, shortening, margarine, emulsifying agent, corn starch, baking powder, salt, citric acid, xanthan gum), Strawberry, Red grapes, Simple syrup(water, sugar, lemon juice), Blackberry, Blueberry, Raspberry, Glaze",
      image: "../images/cake/cloud-cake2.png",
      nutrition: {
          calories: 270,
          fat: '19(g)',
          fatS:'11(g)',
          tfat:'1(g)',
          sugar: '14(g)',
          carbs: '21(g)',
          protein: '4(g)',
        },
    },
    {
      id: 8,
      category: "Cake",
      name: "Strawberry Cloud Cake",
      ingredients: "Strawberry cloud cream(heavy cream, whipping cream, sugar, strawberry syrup), Strawberry cake sheet[liquid egg, sugar, wheat flour, butter, strawberry syrup, strawberry powder, emulsifying agent, baking powder, sea salt, food coloring(pink)], Strawberry, Simple syrup (water, sugar, lemon), Red grape, Blueberry, Decorative chocolate, Glaze",
      image: "../images/cake/strawberry-cloud.webp",
      nutrition: {
          calories: 270,
          fat: '18(g)',
          fatS:'11(g)',
          tfat:'0(g)',
          sugar: '17(g)',
          carbs: '41(g)',
          protein: '3(g)',
        },
    },
    {
      id: 9,
      category: "Cake",
      name: "Green Tea Cloud Cake",
      ingredients: "Green tea cake sheet(liquid egg, sugar, wheat flour, butter, green tea powder, emulsifying agent, baking powder, sea salt, food color), Cloud cream[heavy cream(milk), whipping cream, sugar], Strawberry, Simple syrup (water, sugar, lemon), Green tea sheet crumb, Blackberry, Green grape, Raspberry, Blueberry, Glaze",
      image: "../images/cake/green-tea.webp",
      nutrition: {
          calories: 230,
          fat: '14(g)',
          fatS:'9(g)',
          tfat:'0(g)',
          sugar: '15(g)',
          carbs: '23(g)',
          protein: '4(g)',
        },
    },
    {
      id: 10,
      category: "Cake",
      name: "Peach Cream Cake",
      ingredients: "Cream, Whole egg, Whipping cream, Apricot jam, Sugar, Frozen peach, White chocolate, Wheat flour, Water, Milk, Coating chocolate, Yogurt powder, Corn syrup, Shortening, Margarine, Cheese, Emulsifying agent, Corn starch, Baking powder, Peach flavored syrup, Salt, Cake stabilizer, Citric acid, Xanthan gum, Sugar powder",
      image: "../images/cake/peach-cream.webp",
      nutrition: {
          calories: 260,
          fat: '15(g)',
          fatS:'8(g)',
          tfat:'0.5(g)',
          sugar: '21(g)',
          carbs: '30(g)',
          protein: '5(g)',
        },
    },
    {
      id: 11,
      category: "Cake",
      name: "Triple Berry Cloud",
      ingredients: "Cloud cream[heavy cream(milk), whipped cream, sugar], White cake sheet(whole egg, wheat flour, sugar, egg white, milk, corn syrup, shortening, margarine, emulsifying agent, corn starch, baking powder, salt, citric acid, xanthan gum), Strawberry, Raspberry, Blueberry, Strawberry cream[heavy cream(milk), whipped cream, sugar, strawberry syrup], Simple syrup(water, sugar, lemon juice), Glaze",
      image: "../images/cake/triple-berry.png",
      nutrition: {
          calories: 250,
          fat: '18(g)',
          fatS:'11(g)',
          tfat:'0.5(g)',
          sugar: '12(g)',
          carbs: '19(g)',
          protein: '3(g)',
        },
    },
    {
      id: 12,
      category: "Cake",
      name: "Mango Cloud 3",
      ingredients: "Mango cream[heavy cream(milk), mango puree, whipped cream, sugar, mango compound], White cake sheet(whole egg, wheat flour, sugar, egg white, milk, corn syrup, shortening, margarine, emulsifying agent, corn starch, baking powder, salt, citric acid, xanthan gum), Mango, Blueberry, Cloud cream[heavy cream(milk), whipped cream, sugar], Simple syrup(water, sugar, lemon juice), Mango glaze(Mango compound, water, sugar, lemon juice), Glaze",
      image: "../images/cake/mango-cloud3.webp",
      nutrition: {
          calories: 290,
          fat: '21(g)',
          fatS:'12(g)',
          tfat:'1(g)',
          sugar: '17(g)',
          carbs: '23(g)',
          protein: '4(g)',
        },
    },
    {
      id: 13,
      category: "Cake",
      name: "Mango Cloud 2",
      ingredients: "Mango cream[heavy cream(milk), mango puree, whipped cream, sugar, mango compound], White cake sheet(whole egg, wheat flour, sugar, egg white, milk, corn syrup, shortening, margarine, emulsifying agent, corn starch, baking powder, salt, citric acid, xanthan gum), Mango, Blueberry, Cloud cream[heavy cream(milk), whipped cream, sugar], Simple syrup(water, sugar, lemon juice), Glaze",
      image: "../images/cake/mango-cloud2.webp",
      nutrition: {
          calories: 290,
          fat: '21(g)',
          fatS:'13(g)',
          tfat:'0.5(g)',
          sugar: '17(g)',
          carbs: '23(g)',
          protein: '4(g)',
        },
    },
    {
      id: 14,
      category: "Cake",
      name: "Mocha Cloud",
      ingredients: "Mocha cloud cream[heavy cream(milk), coffee extract, whipped cream, sugar], Mocha cake sheet(liquid egg, sugar, wheat flour, butter, emulsifying agent, coffee extract, baking powder, sea salt), Strawberry, Cloud cream[heavy cream(milk), whipped cream, sugar], Cake syrup(water, sugar), Caramel sauce, Green grape, Raspberry, Blueberry, Glaze",
      image: "../images/cake/mocha-cloud.webp",
      nutrition: {
          calories: 310,
          fat: '24(g)',
          fatS:'15(g)',
          tfat:'0.5(g)',
          sugar: '13(g)',
          carbs: '21(g)',
          protein: '4(g)',
        },
    },
    {
      id: 15,
      category: "Cake",
      name: "Choco Cloud",
      ingredients: "Cloud cream[heavy cream(milk), whipping cream, sugar], Choco cake sheet(liquid egg, sugar, wheat flour, butter, dark cocoa powder, dough improver, baking powder, sea salt), Semisweet chocolate, Strawberry, Simple syrup (water, sugar, lemon), Cocoa powder, Semisweet chocolate",
      image: "../images/cake/choco-cloud.webp",
      nutrition: {
          calories: 340,
          fat: '25(g)',
          fatS:'15(g)',
          tfat:'0(g)',
          sugar: '20(g)',
          carbs: '29(g)',
          protein: '5(g)',
        },
    },
    {
      id: 16,
      category: "Cake",
      name: "Earl Grey Cloud",
      ingredients: "Earl Grey cloud cream[heavy cream(milk), Earl Grey Extract, whipped cream, sugar], Earl Grey cake sheet(liquid egg, sugar, wheat flour, butter, emulsifying agent, earl grey extract, baking powder, sea salt), Cloud cream[heavy cream(milk), whipped cream, sugar]",
      image: "../images/cake/earl-grey.png",
      nutrition: {
          calories: 310,
          fat: '24(g)',
          fatS:'15(g)',
          tfat:'0.5(g)',
          sugar: '14(g)',
          carbs: '19(g)',
          protein: '4(g)',
        },
    },
  ],
},
pastry: {
  headerImage: "../images/menu-headers/pastry-header.webp",
  items: [
    {
      id: 1,
      category: "Pastry",
      name: "Kimchi Croquette",
      ingredients: "Filling[kimchi, onion, water, green bell pepper, cellophane noodles, spicy sauce, concentrated soy protein, bread crumb, rice wine, soy sauce, soybean oil, ginger, garlic, red pepper powder, sugar, sauce(broth), black pepper], Dough(wheat flour, water, whole egg, shortening, sugar, yeast, dough improver, cheese flavored syrup, sea salt, baking powder, yeast food), Bread crumb, Soybean oil, Parsley flakes",
      image: "../images/pastry/kimchi-croquette.webp",
      nutrition: {
          calories: 300,
          fat: '13(g)',
          fatS:'2(g)',
          tfat:'0.5(g)',
          sugar: '6(g)',
          carbs: '37(g)',
          protein: '8(g)',
        },
    },
    {
      id: 2,
      category: "Pastry",
      name: "Caramel Apple Pie",
      ingredients: "Bread dough(wheat flour, apple pie filling, prepared edible fat, water, caramel, sugar, mixed skim milk powder, sea salt), Egg yolk. Glaze",
      image: "../images/pastry/caramel-apple.webp",
      nutrition: {
          calories: 250,
          fat: '15(g)',
          fatS:'7(g)',
          tfat:'2.5(g)',
          sugar: '6(g)',
          carbs: '24(g)',
          protein: '4(g)',
        },
    },
    {
      id: 3,
      category: "Pastry",
      name: "Almond Croissant",
      ingredients: "Croissant[wheat flour, butter, water, sugar, yeast, whole milk powder, eggs, salt, wheat gluten, food enzymes, ascorbic acid], Almond cream[whole egg, margarine, sugar, almond powder, wheat flour, salt], Sliced almond, Sugar powder",
      image: "../images/pastry/almond-croissant.webp",
      nutrition: {
          calories: 610,
          fat: '45(g)',
          fatS:'13(g)',
          tfat:'0(g)',
          sugar: '11(g)',
          carbs: '40(g)',
          protein: '16(g)',
        },
    },
    {
      id: 4,
      category: "Pastry",
      name: "Fruit Pastry",
      ingredients: "Pastry dough(wheat flour, butter, water, sugar, yeast, whole egg, sea salt, dough improver, mixed skim milk powder, yeast food), Cloud cream[heavy cream(milk), whipped cream, sugar], Parisian cream, Strawberry, Blueberry, Green grapes, Raspberry, Red grapes, Egg wash(egg, water), Glaze, Sugar powder",
      image: "../images/pastry/fruit-pastry.jpeg",
      nutrition: {
          calories: 410,
          fat: '27(g)',
          fatS:'15(g)',
          tfat:'0(g)',
          sugar: '14(g)',
          carbs: '38(g)',
          protein: '6(g)',
        },
    },
    {
      id: 5,
      category: "Pastry",
      name: "Pain Au Chocolat",
      ingredients: "Wheat flour, Butter, Water, Chocolate, Sugar, Yeast, Whole milk powder, Wheat gluten, Salt, Food enzymes, Ascorbic acid, Egg wash(egg, water)",
      image: "../images/pastry/pain-au.jpeg",
      nutrition: {
          calories: 260,
          fat: '14(g)',
          fatS:'9(g)',
          tfat:'0(g)',
          sugar: '8(g)',
          carbs: '28(g)',
          protein: '6(g)',
        },
    },
    {
      id: 6,
      category: "Pastry",
      name: "Strawberry Croissant",
      ingredients: "Croissant[wheat flour, butter, water, sugar, yeast, whole milk powder, eggs, salt, wheat gluten, food enzymes, ascorbic acid], Fresh strawberries, Cloud cream[heavy cream(milk), whipped cream, sugar], Sugar powder",
      image: "../images/pastry/strawberry-croissant.webp",
      nutrition: {
          calories: 300,
          fat: '20(g)',
          fatS:'12(g)',
          tfat:'0(g)',
          sugar: '28(g)',
          carbs: '28(g)',
          protein: '5(g)',
        },
    },
    {
      id: 7,
      category: "Pastry",
      name: "Croissant",
      ingredients: "Croissant[wheat flour, butter, water, sugar, yeast, whole milk powder, eggs, salt, wheat gluten, food enzymes, ascorbic acid]",
      image: "../images/pastry/croissant.webp",
      nutrition: {
          calories: 280,
          fat: '16(g)',
          fatS:'10(g)',
          tfat:'0(g)',
          sugar: '6(g)',
          carbs: '29(g)',
          protein: '5(g)',
        },
    },
    {
      id: 8,
      category: "Pastry",
      name: "Yuzu Pie",
      ingredients: "Yuzu pie dough(wheat flour, prepared edible fat, milk, sugar, egg yolk, prepared edible fat, corn starch, wheat flour, water, citron jam, sugar, mixed skim milk powder, sea salt), Sugar",
      image: "../images/pastry/yuzu-pie.webp",
      nutrition: {
          calories: 420,
          fat: '27(g)',
          fatS:'12(g)',
          tfat:'5(g)',
          sugar: '15(g)',
          carbs: '39(g)',
          protein: '5(g)',
        },
    },
    {
      id: 9,
      category: "Pastry",
      name: "Chocolate Croissant",
      ingredients: "Croissant[wheat flour, butter, water, sugar, yeast, whole milk powder, eggs, salt, wheat gluten, food enzymes, ascorbic acid], Coating chocolate(dark), Sliced almond",
      image: "../images/pastry/chocolate-croissant.webp",
      nutrition: {
          calories: 480,
          fat: '31(g)',
          fatS:'18(g)',
          tfat:'0(g)',
          sugar: '20(g)',
          carbs: '46(g)',
          protein: '8(g)',
        },
    },
    {
      id: 10,
      category: "Pastry",
      name: "Spinach Feta Danish",
      ingredients: "Unbleached enriched flour, Spinach and feta filling, Butter, Water, Sugar, Yeast, Liquid whole eggs, Salt, Wheat gluten, Food enzymes(xylanase, amylase), Ascorbic acid, Dried whole eggs, Skim milk powder, Soy flour",
      image: "../images/pastry/spinach-feta.webp",
      nutrition: {
          calories: 320,
          fat: '18(g)',
          fatS:'11(g)',
          tfat:'0(g)',
          sugar: '5(g)',
          carbs: '32(g)',
          protein: '7(g)',
        },
    },
    {
      id: 11,
      category: "Pastry",
      name: "Garlic & Cheese Croissant",
      ingredients: "Croissant[wheat flour, butter, water, sugar, yeast, whole milk powder, eggs, salt, wheat gluten, food enzymes, garlic, ascorbic acid], Coating cheese and garlic",
      image: "../images/pastry/garlic-cheese.jpeg",
      nutrition: {
          calories: 350,
          fat: '15(g)',
          fatS:'7(g)',
          tfat:'0(g)',
          sugar: '10(g)',
          carbs: '35(g)',
          protein: '7(g)',
        },
    },
    {
      id: 12,
      category: "Pastry",
      name: "Apple Jam Mont Blanc Pastry",
      ingredients: "Pastry dough(wheat flour, butter, water, sugar, yeast, whole egg, sea salt, dough improver, mixed skim milk powder, yeast food), Cloud cream[heavy cream(milk), whipped cream, sugar], Apples, Egg wash(egg, water), Glaze, Sugar powder",
      image: "../images/pastry/apple-jam.jpeg",
      nutrition: {
          calories: 450,
          fat: '24(g)',
          fatS:'11(g)',
          tfat:'0(g)',
          sugar: '14(g)',
          carbs: '39(g)',
          protein: '8(g)',
        },
    },
  ],
},
  coffee: {
  headerImage: "../images/menu-headers/coffee-header.webp",
  items: [
    {
      id: 0,
      category: "Coffee",
      name: "Red Velvet Latte",
      ingredients: "Red Velvet Cake, milk (dairy or plant-based), espresso or strong brewed coffee, and ice cubes",
      image: "../images/coffee/red-velvet.jpeg",
      nutrition: {
          calories: 220,
          fat: '7(g)',
          fatS:'3.5(g)',
          tfat:'0(g)',
          sugar: '40(g)',
          carbs: '39(g)',
          protein: '7(g)',
        },
    },
    {
      id: 1,
      category: "Coffee",
      name: "Iced Red Velvet Latte",
      ingredients: "Red Velvet cake, espresso shots diluted with hot water",
      image: "../images/coffee/iced-red.jpeg",
      nutrition: {
          calories: 5,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '0(g)',
          carbs: '0(g)',
          protein: '0(g)',
        },
    },
    {
      id: 2,
      category: "Coffee",
      name: "Iced Cafe Latte",
      ingredients: "Espresso or strong brewed coffee, milk (dairy or plant-based), and ice cubes",
      image: "../images/coffee/iced-cafe-latte.png",
      nutrition: {
          calories: 170,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '14(g)',
          carbs: '14(g)',
          protein: '9(g)',
        },
    },
    {
      id: 3,
      category: "Coffee",
      name: "Iced Cafe Mocha",
      ingredients: "Espresso or strong brewed coffee, milk (dairy or plant-based), chocolate syrup, and ice cubes",
      image: "../images/coffee/iced-cafe-mocha.png",
      nutrition: {
          calories: 310,
          fat: '8(g)',
          fatS:'4(g)',
          tfat:'0(g)',
          sugar: '36(g)',
          carbs: '49(g)',
          protein: '9(g)',
        },
    },
    {
      id: 4,
      category: "Coffee",
      name: "Iced Vanilla Latte",
      ingredients: "Espresso or strong brewed coffee, cold milk (dairy or plant-based), and vanilla syrup over ice",
      image: "../images/coffee/iced-vanilla-latte.png",
      nutrition: {
          calories: 230,
          fat: '7(g)',
          fatS:'4(g)',
          tfat:'0(g)',
          sugar: '34(g)',
          carbs: '34(g)',
          protein: '7(g)',
        },
    },
    {
      id: 5,
      category: "Coffee",
      name: "Iced Caramel Macchiato",
      ingredients: "Espresso, milk (dairy or plant-based), caramel syrup, and ice",
      image: "../images/coffee/iced-caramel-macchiato.png",
      nutrition: {
          calories: 290,
          fat: '8(g)',
          fatS:'4(g)',
          tfat:'0(g)',
          sugar: '65(g)',
          carbs: '45(g)',
          protein: '7(g)',
        },
    },
    {
      id: 6,
      category: "Coffee",
      name: "Iced Lavender Latte",
      ingredients: "Lavender syrup, milk (dairy or plant-based), espresso or strong brewed coffee, and ice cubes",
      image: "../images/coffee/iced-lavender-latte.png",
      nutrition: {
          calories: 240,
          fat: '6(g)',
          fatS:'3.5(g)',
          tfat:'0(g)',
          sugar: '38(g)',
          carbs: '39(g)',
          protein: '7(g)',
        },
    },
    {
      id: 7,
      category: "Coffee",
      name: "Cafe Mocha",
      ingredients: "Espresso or strong brewed coffee, milk (dairy or plant-based), and chocolate syrup",
      image: "../images/coffee/cafe-mocha.png",
      nutrition: {
          calories: 300,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '45(g)',
          carbs: '42(g)',
          protein: '10(g)',
        },
    },
    {
      id: 8,
      category: "Coffee",
      name: "Cafe Latte",
      ingredients: "Espresso or strong brewed coffee and steamed milk (dairy or plant-based)",
      image: "../images/coffee/cafe-latte.png",
      nutrition: {
          calories: 180,
          fat: '10(g)',
          fatS:'6(g)',
          tfat:'0(g)',
          sugar: '14(g)',
          carbs: '14(g)',
          protein: '9(g)',
        },
    },
    {
      id: 9,
      category: "Coffee",
      name: "Cappuccino",
      ingredients: "Espresso, steamed milk (dairy or plant-based), and foamed milk",
      image: "../images/coffee/cappuccino.png",
      nutrition: {
          calories: 170,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '14(g)',
          carbs: '14(g)',
          protein: '9(g)',
        },
    },
    {
      id: 10,
      category: "Coffee",
      name: "Caramel Macchiato",
      ingredients: "Espresso, steamed milk (dairy or plant-based), and caramel syrup",
      image: "../images/coffee/caramel-macchiato.png",
      nutrition: {
          calories: 300,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '45(g)',
          carbs: '41(g)',
          protein: '9(g)',
        },
    },
    {
      id: 11,
      category: "Coffee",
      name: "Lavender Latte",
      ingredients: "Espresso or strong brewed coffee, milk (dairy or plant-based), and lavender syrup",
      image: "../images/coffee/lavender-latte.png",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '37(g)',
          protein: '9(g)',
        },
    },
    {
      id: 12,
      category: "Coffee",
      name: "Vanilla Latte",
      ingredients: "Espresso or strong brewed coffee, steamed milk (dairy or plant-based), and vanilla syrup",
      image: "../images/coffee/vanilla-latte.png",
      nutrition: {
          calories: 210,
          fat: '8(g)',
          fatS:'4.5(g)',
          tfat:'0(g)',
          sugar: '27(g)',
          carbs: '27(g)',
          protein: '7(g)',
        },
    },
    {
      id: 13,
      category: "Coffee",
      name: "Cold Brew Tonic",
      ingredients: "Cold brew coffee and tonic water over ice",
      image: "../images/coffee/cold-brew-tonic.png",
      nutrition: {
          calories: 100,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '26(g)',
          carbs: '26(g)',
          protein: '0(g)',
        },
    },
    {
      id: 14,
      category: "Coffee",
      name: "Iced Americano",
      ingredients: "Espresso shots and cold water over ice",
      image: "../images/coffee/iced-americano.png",
      nutrition: {
          calories: 5,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '0(g)',
          carbs: '0(g)',
          protein: '0(g)',
        },
    },
    {
      id: 15,
      category: "Coffee",
      name: "Cafe Americano",
      ingredients: "Espresso shots diluted with hot water",
      image: "../images/coffee/cafe-americano.jpg",
      nutrition: {
          calories: 5,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '0(g)',
          carbs: '0(g)',
          protein: '0(g)',
        },
    },
  ],
},
  tea: {
    headerImage: "../images/menu-headers/tea-header.webp",
    items: [
      {
        id: 0,
        category: "Tea",
        name: "Iced Strawberry & Flower Tea Latte",
        ingredients: "Strawberry powder, milk (dairy or plant-based), honey, dried culinary lavender (strained), and optionally, strawberry syrup for added flavor",
        image: "../images/tea/iced-strawberry.jpeg",
        nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
      },
      {
        id: 1,
        category: "Tea",
        name: "Strawberry & Flower Tea Latte",
        ingredients: "Strawberry powder, milk (dairy or plant-based), honey, dried culinary lavender (strained), and optionally, strawberry syrup for added flavor",
        image: "../images/tea/strawberry-tea.jpeg",
        nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
      },
      {
        id: 2,
        category: "Tea",
        name: "Ube Latte",
        ingredients: "Ube (purple yam) paste or extract, milk (dairy or plant-based), sweetened condensed milk or sweetener, and espresso or strong brewed coffee",
        image: "../images/tea/ube-latte.png",
        nutrition: {
          calories: 240,
          fat: '10(g)',
          fatS:'6(g)',
          tfat:'0(g)',
          sugar: '29(g)',
          carbs: '29(g)',
          protein: '9(g)',
        },
      },
      {
        id: 3,
        category: "Tea",
        name: "Iced Ube Latte",
        ingredients: "Ube (purple yam) paste or extract, milk (dairy or plant-based), sweetened condensed milk or sweetener, ice cubes, and optionally, espresso or strong brewed coffee",
        image: "../images/tea/iced-bbe-latte.png",
        nutrition: {
          calories: 230,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '54(g)',
          carbs: '60(g)',
          protein: '1(g)',
        },
      },
      {
        id: 4,
        category: "Tea",
        name: "Iced Matcha Latte",
        ingredients: "Matcha powder, milk (dairy or plant-based), sweetener, ice cubes, and optionally, whipped cream for topping",
        image: "../images/tea/iced-matcha-latte.png",
        nutrition: {
          calories: 210,
          fat: '7(g)',
          fatS:'4(g)',
          tfat:'0(g)',
          sugar: '29(g)',
          carbs: '29(g)',
          protein: '9(g)',
        },
      },
      {
        id: 5,
        category: "Tea",
        name: "Matcha Latte",
        ingredients: "Matcha powder, milk (dairy or plant-based), and sweetener",
        image: "../images/tea/matcha-latte.png",
        nutrition: {
          calories: 220,
          fat: '8(g)',
          fatS:'4.5(g)',
          tfat:'0(g)',
          sugar: '27(g)',
          carbs: '27(g)',
          protein: '10(g)',
        },
      },
      {
        id: 6,
        category: "Tea",
        name: "Iced Green Tea",
        ingredients: "Green tea bags or loose leaf tea, water, ice cubes, and optionally, sweetener or lemon for flavor",
        image: "../images/tea/iced-green-tea.png",
        nutrition: {
          calories: 60,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '14(g)',
          carbs: '14(g)',
          protein: '1(g)',
        },
      },
      {
        id: 7,
        category: "Tea",
        name: "Iced Black Tea",
        ingredients: "Black tea bags or loose leaf tea, water, ice cubes, and optionally, sweetener or lemon for flavor",
        image: "../images/tea/iced-black-tea.png",
        nutrition: {
          calories: 60,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '15(g)',
          carbs: '16(g)',
          protein: '0(g)',
        },
      },
      {
        id: 8,
        category: "Tea",
        name: "Hot Green Tea",
        ingredients: "Green tea bags or loose leaf tea, hot water, and optionally, sweetener",
        image: "../images/tea/hot-green-tea.png",
        nutrition: {
          calories: 60,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '16(g)',
          carbs: '16(g)',
          protein: '0(g)',
        },
      },
      {
        id: 9,
        category: "Tea",
        name: "Chamomile Tea",
        ingredients: "Chamomile tea bags or loose leaf tea, hot water, and optionally, honey or lemon for flavor",
        image: "../images/tea/chamomile-tea.png",
        nutrition: {
          calories: 60,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '16(g)',
          carbs: '16(g)',
          protein: '0(g)',
        },
      },
    ],
  },
  blended: {
    headerImage: "../images/menu-headers/blended-header.jpg",
    items: [
      {
        id: 1,
        category: "Blended",
        name: "Strawberry Smoothie",
        ingredients: "Fresh or frozen strawberries, yogurt (plain or vanilla), milk (dairy or plant-based), honey, and ice cubes",
        image: "../images/blended/strawberry-smoothie.png",
        nutrition: {
          calories: 230,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '54(g)',
          carbs: '60(g)',
          protein: '1(g)',
        },
      },
      {
        id: 2,
        category: "Blended",
        name: "Mango Smoothie",
        ingredients: "Fresh or frozen mangoes, yogurt (plain or vanilla), milk (dairy or plant-based), honey, and ice cubes",
        image: "../images/blended/mango-smoothie.png",
        nutrition: {
          calories: 250,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '54(g)',
          carbs: '66(g)',
          protein: '0(g)',
        },
      },
      {
        id: 3,
        category: "Blended",
        name: "Matcha Frappe",
        ingredients: "Matcha powder, milk (dairy or plant-based), ice cubes, sweetener (optional), and whipped cream (optional)",
        image: "../images/blended/matcha-frappe.png",
        nutrition: {
          calories: 480,
          fat: '11(g)',
          fatS:'7(g)',
          tfat:'0(g)',
          sugar: '79(g)',
          carbs: '86(g)',
          protein: '1(g)',
        },
      },
      {
        id: 4,
        category: "Blended",
        name: "Caramel Frappe",
        ingredients: "Coffee (brewed and cooled), milk (dairy or plant-based), caramel syrup, ice cubes, and whipped cream (optional)",
        image: "../images/blended/caramel-frappe.png",
        nutrition: {
          calories: 430,
          fat: '10(g)',
          fatS:'7(g)',
          tfat:'0(g)',
          sugar: '74(g)',
          carbs: '82(g)',
          protein: '7(g)',
        },
      },
      {
        id: 5,
        category: "Blended",
        name: "Mocha Frappe",
        ingredients: "Coffee (brewed and cooled), milk (dairy or plant-based), chocolate syrup, ice cubes, and whipped cream (optional)",
        image: "../images/blended/mocha-frappe.png",
        nutrition: {
         calories: 330,
          fat: '10(g)',
          fatS:'7(g)',
          tfat:'0(g)',
          sugar: '43(g)',
          carbs: '48(g)',
          protein: '13(g)',
        },
      },
    ],
  },
};

export default data;
