const data = {
  bread: {
  headerImage: "../images/menu-headers/bread-header.webp",
  items: [
    {
      id: 1,
      category: "Bread",
      name: "Bread 1",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 2,
      category: "Bread",
      name: "Bread 2",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 3,
      category: "Bread",
      name: "Bread 3",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 4,
      category: "Bread",
      name: "Bread 4",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 5,
      category: "Bread",
      name: "Bread 5",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 6,
      category: "Bread",
      name: "Bread 6",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 7,
      category: "Bread",
      name: "Bread 7",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 8,
      category: "Bread",
      name: "Bread 8",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 9,
      category: "Bread",
      name: "Bread 9",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 10,
      category: "Bread",
      name: "Bread 10",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 11,
      category: "Bread",
      name: "Bread 11",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 12,
      category: "Bread",
      name: "Bread 12",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 13,
      category: "Bread",
      name: "Bread 13",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 14,
      category: "Bread",
      name: "Bread 14",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 15,
      category: "Bread",
      name: "Bread 15",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 16,
      category: "Bread",
      name: "Bread 16",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
  ],
},
  cakes: {
  headerImage: "../images/menu-headers/cake-header.webp",
  items: [
    {
      id: 1,
      category: "Cake",
      name: "Cake 1",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 2,
      category: "Cake",
      name: "Cake 2",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 3,
      category: "Cake",
      name: "Cake 3",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 4,
      category: "Cake",
      name: "Cake 4",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 5,
      category: "Cake",
      name: "Cake 5",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 6,
      category: "Cake",
      name: "Cake 6",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 7,
      category: "Cake",
      name: "Cake 7",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 8,
      category: "Cake",
      name: "Cake 8",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 9,
      category: "Cake",
      name: "Cake 9",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 10,
      category: "Cake",
      name: "Cake 10",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 11,
      category: "Cake",
      name: "Cake 11",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 12,
      category: "Cake",
      name: "Cake 12",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 13,
      category: "Cake",
      name: "Cake 13",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 14,
      category: "Cake",
      name: "Cake 14",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 15,
      category: "Cake",
      name: "Cake 15",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 16,
      category: "Cake",
      name: "Cake 16",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
  ],
},
pastry: {
  headerImage: "../images/menu-headers/pastry-header.webp",
  items: [
    {
      id: 1,
      category: "Pastry",
      name: "Pastry 1",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 2,
      category: "Pastry",
      name: "Pastry 2",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 3,
      category: "Pastry",
      name: "Pastry 3",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 4,
      category: "Pastry",
      name: "Pastry 4",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 5,
      category: "Pastry",
      name: "Pastry 5",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 6,
      category: "Pastry",
      name: "Pastry 6",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 7,
      category: "Pastry",
      name: "Pastry 7",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 8,
      category: "Pastry",
      name: "Pastry 8",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 9,
      category: "Pastry",
      name: "Pastry 9",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 10,
      category: "Pastry",
      name: "Pastry 10",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 11,
      category: "Pastry",
      name: "Pastry 11",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
    {
      id: 12,
      category: "Pastry",
      name: "Pastry 12",
      ingredients: "",
      image: "",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
    },
  ],
},
  coffee: {
  headerImage: "../images/menu-headers/coffee-header.webp",
  items: [
    {
      id: 1,
      category: "Coffee",
      name: "Iced Lavender Latte",
      ingredients: "Lavender syrup, milk (dairy or plant-based), espresso or strong brewed coffee, and ice cubes",
      image: "../images/coffee/iced-lavender-latte.png",
      nutrition: {
          calories: 240,
          fat: '6(g)',
          fatS:'3.5(g)',
          tfat:'0(g)',
          sugar: '38(g)',
          carbs: '39(g)',
          protein: '7(g)',
        },
    },
    {
      id: 2,
      category: "Coffee",
      name: "Iced Cafe Mocha",
      ingredients: "Espresso or strong brewed coffee, milk (dairy or plant-based), chocolate syrup, and ice cubes",
      image: "../images/coffee/iced-cafe-mocha.png",
      nutrition: {
          calories: 310,
          fat: '8(g)',
          fatS:'4(g)',
          tfat:'0(g)',
          sugar: '36(g)',
          carbs: '49(g)',
          protein: '9(g)',
        },
    },
    {
      id: 3,
      category: "Coffee",
      name: "Iced Cafe Latte",
      ingredients: "Espresso or strong brewed coffee, milk (dairy or plant-based), and ice cubes",
      image: "../images/coffee/iced-cafe-latte.png",
      nutrition: {
          calories: 170,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '14(g)',
          carbs: '14(g)',
          protein: '9(g)',
        },
    },
    {
      id: 4,
      category: "Coffee",
      name: "Cafe Mocha",
      ingredients: "Espresso or strong brewed coffee, milk (dairy or plant-based), and chocolate syrup",
      image: "../images/coffee/cafe-mocha.png",
      nutrition: {
          calories: 300,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '45(g)',
          carbs: '42(g)',
          protein: '10(g)',
        },
    },
    {
      id: 5,
      category: "Coffee",
      name: "Cafe Latte",
      ingredients: "Espresso or strong brewed coffee and steamed milk (dairy or plant-based)",
      image: "../images/coffee/cafe-latte.png",
      nutrition: {
          calories: 180,
          fat: '10(g)',
          fatS:'6(g)',
          tfat:'0(g)',
          sugar: '14(g)',
          carbs: '14(g)',
          protein: '9(g)',
        },
    },
    {
      id: 6,
      category: "Coffee",
      name: "Cappuccino",
      ingredients: "Espresso, steamed milk (dairy or plant-based), and foamed milk",
      image: "",
      nutrition: {
          calories: 170,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '14(g)',
          carbs: '14(g)',
          protein: '9(g)',
        },
    },
    {
      id: 7,
      category: "Coffee",
      name: "Caramel Macchiato",
      ingredients: "Espresso, steamed milk (dairy or plant-based), and caramel syrup",
      image: "../images/coffee/caramel-macchiato.png",
      nutrition: {
          calories: 300,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '45(g)',
          carbs: '41(g)',
          protein: '9(g)',
        },
    },
    {
      id: 8,
      category: "Coffee",
      name: "Lavender Latte",
      ingredients: "Espresso or strong brewed coffee, milk (dairy or plant-based), and lavender syrup",
      image: "../images/coffee/lavender-latte.png",
      nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '37(g)',
          protein: '9(g)',
        },
    },
    {
      id: 9,
      category: "Coffee",
      name: "Vanilla Latte",
      ingredients: "Espresso or strong brewed coffee, steamed milk (dairy or plant-based), and vanilla syrup",
      image: "../images/coffee/vanilla-latte.png",
      nutrition: {
          calories: 210,
          fat: '8(g)',
          fatS:'4.5(g)',
          tfat:'0(g)',
          sugar: '27(g)',
          carbs: '27(g)',
          protein: '7(g)',
        },
    },
    {
      id: 10,
      category: "Coffee",
      name: "Iced Vanilla Latte",
      ingredients: "Espresso or strong brewed coffee, cold milk (dairy or plant-based), and vanilla syrup over ice",
      image: "../images/coffee/iced-vanilla-latte.png",
      nutrition: {
          calories: 230,
          fat: '7(g)',
          fatS:'4(g)',
          tfat:'0(g)',
          sugar: '34(g)',
          carbs: '34(g)',
          protein: '7(g)',
        },
    },
    {
      id: 11,
      category: "Coffee",
      name: "Iced Caramel Macchiato",
      ingredients: "Espresso, milk (dairy or plant-based), caramel syrup, and ice",
      image: "../images/coffee/iced-caramel-macchiato.png",
      nutrition: {
          calories: 290,
          fat: '8(g)',
          fatS:'4(g)',
          tfat:'0(g)',
          sugar: '65(g)',
          carbs: '45(g)',
          protein: '7(g)',
        },
    },
    {
      id: 12,
      category: "Coffee",
      name: "Cold Brew Tonic",
      ingredients: "Cold brew coffee and tonic water over ice",
      image: "../images/coffee/cold-brew-tonic.png",
      nutrition: {
          calories: 100,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '26(g)',
          carbs: '26(g)',
          protein: '0(g)',
        },
    },
    {
      id: 13,
      category: "Coffee",
      name: "Iced Americano",
      ingredients: "Espresso shots and cold water over ice",
      image: "../images/coffee/iced-americano.png",
      nutrition: {
          calories: 5,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '0(g)',
          carbs: '0(g)',
          protein: '0(g)',
        },
    },
    {
      id: 14,
      category: "Coffee",
      name: "Cafe Americano",
      ingredients: "Espresso shots diluted with hot water",
      image: "../images/coffee/cafe-americano.jpg",
      nutrition: {
          calories: 5,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '0(g)',
          carbs: '0(g)',
          protein: '0(g)',
        },
    },
  ],
},
  tea: {
    headerImage: "../images/menu-headers/tea-header.webp",
    items: [
      {
        id: 1,
        category: "Tea",
        name: "Honey Lavender Matcha Latte",
        ingredients: "Matcha powder, milk (dairy or plant-based), honey, dried culinary lavender (strained), and optionally, lavender syrup for added flavor",
        image: "../images/tea/honey-lavender-matcha-latte.png",
        nutrition: {
          calories: 270,
          fat: '9(g)',
          fatS:'5(g)',
          tfat:'0(g)',
          sugar: '39(g)',
          carbs: '41(g)',
          protein: '0(g)',
        },
      },
      {
        id: 2,
        category: "Tea",
        name: "Ube Latte",
        ingredients: "Ube (purple yam) paste or extract, milk (dairy or plant-based), sweetened condensed milk or sweetener, and espresso or strong brewed coffee",
        image: "../images/tea/ube-latte.png",
        nutrition: {
          calories: 240,
          fat: '10(g)',
          fatS:'6(g)',
          tfat:'0(g)',
          sugar: '29(g)',
          carbs: '29(g)',
          protein: '9(g)',
        },
      },
      {
        id: 3,
        category: "Tea",
        name: "Iced Ube Latte",
        ingredients: "Ube (purple yam) paste or extract, milk (dairy or plant-based), sweetened condensed milk or sweetener, ice cubes, and optionally, espresso or strong brewed coffee",
        image: "../images/tea/iced-bbe-latte.png",
        nutrition: {
          calories: 230,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '54(g)',
          carbs: '60(g)',
          protein: '1(g)',
        },
      },
      {
        id: 4,
        category: "Tea",
        name: "Iced Matcha Latte",
        ingredients: "Matcha powder, milk (dairy or plant-based), sweetener, ice cubes, and optionally, whipped cream for topping",
        image: "../images/tea/iced-matcha-latte.png",
        nutrition: {
          calories: 210,
          fat: '7(g)',
          fatS:'4(g)',
          tfat:'0(g)',
          sugar: '29(g)',
          carbs: '29(g)',
          protein: '9(g)',
        },
      },
      {
        id: 5,
        category: "Tea",
        name: "Matcha Latte",
        ingredients: "Matcha powder, milk (dairy or plant-based), and sweetener",
        image: "../images/tea/matcha-latte.png",
        nutrition: {
          calories: 220,
          fat: '8(g)',
          fatS:'4.5(g)',
          tfat:'0(g)',
          sugar: '27(g)',
          carbs: '27(g)',
          protein: '10(g)',
        },
      },
      {
        id: 6,
        category: "Tea",
        name: "Iced Green Tea",
        ingredients: "Green tea bags or loose leaf tea, water, ice cubes, and optionally, sweetener or lemon for flavor",
        image: "../images/tea/iced-green-tea.png",
        nutrition: {
          calories: 60,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '14(g)',
          carbs: '14(g)',
          protein: '1(g)',
        },
      },
      {
        id: 7,
        category: "Tea",
        name: "Iced Black Tea",
        ingredients: "Black tea bags or loose leaf tea, water, ice cubes, and optionally, sweetener or lemon for flavor",
        image: "../images/tea/iced-black-tea.png",
        nutrition: {
          calories: 60,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '15(g)',
          carbs: '16(g)',
          protein: '0(g)',
        },
      },
      {
        id: 8,
        category: "Tea",
        name: "Hot Green Tea",
        ingredients: "Green tea bags or loose leaf tea, hot water, and optionally, sweetener",
        image: "../images/tea/hot-green-tea.png",
        nutrition: {
          calories: 60,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '16(g)',
          carbs: '16(g)',
          protein: '0(g)',
        },
      },
      {
        id: 9,
        category: "Tea",
        name: "Chamomile Tea",
        ingredients: "Chamomile tea bags or loose leaf tea, hot water, and optionally, honey or lemon for flavor",
        image: "../images/tea/chamomile-tea.png",
        nutrition: {
          calories: 60,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '16(g)',
          carbs: '16(g)',
          protein: '0(g)',
        },
      },
    ],
  },
  blended: {
    headerImage: "../images/menu-headers/blended-header.jpg",
    items: [
      {
        id: 1,
        category: "Blended",
        name: "Strawberry Smoothie",
        ingredients: "Fresh or frozen strawberries, yogurt (plain or vanilla), milk (dairy or plant-based), honey, and ice cubes",
        image: "../images/blended/strawberry-smoothie.png",
        nutrition: {
          calories: 230,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '54(g)',
          carbs: '60(g)',
          protein: '1(g)',
        },
      },
      {
        id: 2,
        category: "Blended",
        name: "Mango Smoothie",
        ingredients: "Fresh or frozen mangoes, yogurt (plain or vanilla), milk (dairy or plant-based), honey, and ice cubes",
        image: "../images/blended/mango-smoothie.png",
        nutrition: {
          calories: 250,
          fat: '0(g)',
          fatS:'0(g)',
          tfat:'0(g)',
          sugar: '54(g)',
          carbs: '66(g)',
          protein: '0(g)',
        },
      },
      {
        id: 3,
        category: "Blended",
        name: "Matcha Frappe",
        ingredients: "Matcha powder, milk (dairy or plant-based), ice cubes, sweetener (optional), and whipped cream (optional)",
        image: "../images/blended/matcha-frappe.png",
        nutrition: {
          calories: 480,
          fat: '11(g)',
          fatS:'7(g)',
          tfat:'0(g)',
          sugar: '79(g)',
          carbs: '86(g)',
          protein: '1(g)',
        },
      },
      {
        id: 4,
        category: "Blended",
        name: "Caramel Frappe",
        ingredients: "Coffee (brewed and cooled), milk (dairy or plant-based), caramel syrup, ice cubes, and whipped cream (optional)",
        image: "../images/blended/caramel-frappe.png",
        nutrition: {
          calories: 430,
          fat: '10(g)',
          fatS:'7(g)',
          tfat:'0(g)',
          sugar: '74(g)',
          carbs: '82(g)',
          protein: '7(g)',
        },
      },
      {
        id: 5,
        category: "Blended",
        name: "Mocha Frappe",
        ingredients: "Coffee (brewed and cooled), milk (dairy or plant-based), chocolate syrup, ice cubes, and whipped cream (optional)",
        image: "../images/blended/mocha-frappe.png",
        nutrition: {
         calories: 330,
          fat: '10(g)',
          fatS:'7(g)',
          tfat:'0(g)',
          sugar: '43(g)',
          carbs: '48(g)',
          protein: '13(g)',
        },
      },
    ],
  },
};

export default data;
